namespace ONNX_Runner.Models;

/// <summary>
/// Configuration for post-processing Digital Signal Processing (DSP) algorithms.
/// Highly useful for cleaning up high-frequency "hiss" or artifacts generated by the neural networks.
/// </summary>
public class DspSettings
{
    /// <summary>
    /// Global toggle for the anti-aliasing low-pass filter.
    /// </summary>
    public bool EnableLowPassFilter { get; set; } = true;

    /// <summary>
    /// The cutoff frequency in Hertz. Any audio frequencies above this value will be smoothly attenuated.
    /// 7500Hz is a sweet spot for removing robotic digital artifacts while preserving human voice clarity.
    /// </summary>
    public float LowPassCutoffFrequency { get; set; } = 7500f;

    /// <summary>
    /// Resonance Q-Factor. 0.707 (Butterworth) provides the most natural, flat frequency response without peaking.
    /// </summary>
    public float LowPassQFactor { get; set; } = 0.707f;
}