<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- STT Runner: A lightweight, cross-platform speech-to-text server using Whisper (Vulkan) and Silero VAD. -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- AllowUnsafeBlocks is required for high-performance memory operations -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    
    <AssemblyName>Simple Whisper STT</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>MrHruhorii</Authors>
    <Description>A lightweight, cross-platform STT server using Whisper (Vulkan) and Silero VAD.</Description>
  </PropertyGroup>
  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.25.1" />
    
    <!-- Whisper.net and its runtimes -->
    <PackageReference Include="Whisper.net" Version="1.9.0" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.0" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.0" />
  </ItemGroup>
  <!-- Ensure appsettings.json is copied to the output directory -->
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>